# .circleci/config.yml
version: 2

dependencies:
  pre:
    - gem install bundler

jobs:
  build-and-test:
    macos:
      xcode: "9.0"
    docker:
      - image: circleci/ruby:2.0
    steps:
      - checkout
      - run: gem install fastlane -v 2.88.0
      - run: echo "$GC_KEYS" > "gc_eys.json"
      - run: fastlane build

workflows:
  version: 2
  build-test-adhoc:
    jobs:
      - build-and-test
