# .circleci/config.yml
version: 2

dependencies:
  pre:
    - gem install bundler

jobs:
  build-and-test:
    macos:
      xcode: "10.1.0"
    steps:
      - checkout
      - run: bundle install
      - run: echo "$GC_KEYS" > "gc_keys.json"
      - run: fastlane build

workflows:
  version: 2
  build-test-adhoc:
    jobs:
      - build-and-test
