# .circleci/config.yml
version: 2

dependencies:
  pre:
    - gem install bundler

jobs:
  build-and-test:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run:
          name: Setup Build
          command: |
            mkdir -p ~/test-reports
            echo "2.3" > .ruby-version
            gem update --system
      - run: yes | gem update fastlane
      # - run: fastlane test

workflows:
  version: 2
  build-test-adhoc:
    jobs:
      - build-and-test
