# .circleci/config.yml
version: 2

dependencies:
  pre:
    - gem install bundler

jobs:
  build-and-test:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run: bundle update
      - run: bundle exec fastlane test

workflows:
  version: 2
  build-test-adhoc:
    jobs:
      - build-and-test
