# fastlane/Fastfile
default_platform :ios

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Runs all the tests"
  lane :test do
    puts "test test"
  end

  desc "Ad-hoc build"
  lane :adhoc do
    puts "test adhoc"
  end
end