# fastlane/Fastfile
default_platform :ios

platform :ios do
  before_all do
    # setup_circle_ci
  end

  desc "Runs all the tests"
  lane :test do
    puts "test test"
  end

  desc "Ad-hoc build"
  lane :adhoc do
    puts "test adhoc"
  end

  desc "Runs all the tests"
  lane :build do
    match(
      google_cloud_bucket_name: "joshdholtz-match",
      storage_mode: "google_cloud",
      app_identifier: 'com.joshholtz.FastlaneApp',
      type: 'appstore',
      username: 'me@joshholtz.com',
      readonly: true
    )

    gym()
  end
end
